###
GET http://localhost:8000/

### Revenue
GET http://localhost:8000/api/finance/revenue

### Expense
GET http://localhost:8000/api/finance/expense

### gross-profit-margin
GET http://localhost:8000/api/finance/gross-profit-margin

### net-profit-margin
GET http://localhost:8000/api/finance/net-profit-margin

### working-capital-ratio"
GET http://localhost:8000/api/finance/working-capital-ratio